name: keep alive

on:
  schedule:
    - cron: '*/5 * * * *'
jobs:
  build:
    name: keep alive
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          if [ $(curl -LI https://kalipare.com -o /dev/null -w '%{http_code}\n' -s) == "200" ]
          then
              echo "SUCCESS ✅" > README.md
          else
              echo "FAILURE ❌" > README.md
          fi
      - uses: stefanzweifel/git-auto-commit-action@v4
