name: gcp function keep alive

on:
  schedule:
    - cron: '*/15 * * * *'
jobs:
  build:
    name: keep alive
    runs-on: ubuntu-latest
    steps:
      - run: |
          OUTPUT=`curl --write-out '%{http_code}' --silent --output /dev/null -X GET "https://kalipare.com"`
          if [ $CODE!="200" ] 
          then
              echo "FAILURE"
          else
              echo "SUCCESS"
          fi
