name: keep alive

on:
  schedule:
    - cron: '*/5 * * * *'
jobs:
  build:
    name: keep alive
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          CODE=`curl --write-out '%{http_code}' --silent --output /dev/null -X GET "https://kalipare.com"`
          if [ $CODE!="200" ] 
          then
              echo "FAILURE ❌" > README.md
          else
              echo "SUCCESS ✅" > README.md
          fi
      - uses: stefanzweifel/git-auto-commit-action@v4
